Board:
  type: object
  inherits: ['Node']
  config:
    name: Board
    interfaces: ['Node']
    description: 'I am the Board description!'
    fields:
      id:
        type: 'ID!'
      background:
        type: 'URI'
      name:
        type: 'String!'
      categories:
        type: '[Category!]!'
      team:
        type: 'Team!'
