Mutation:
  type: object
  config:
    name: Mutation
    fields:
      loginUser:
        description: 'Log the user'
        access: "@=isAnonymous()"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: LoginUserInput
          payloadType: LoginUserPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\User\\LoginUserMutation", [value])'
      changeTicketPosition:
        description: 'Change a ticket position'
        access: "@=isAuthenticated()"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: ChangeTicketPositionInput
          payloadType: ChangeTicketPositionPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\ChangeTicketPositionMutation", [value])'
