Team:
  type: object
  inherits: ['Node']
  config:
    name: Team
    fieldsDefaultAccess: "@=hasPermission(value, 'VIEW')"
    interfaces: ['Node']
    fields:
      id:
        type: 'ID!'
      members:
        type: '[User!]!'
      name:
        type: 'String!'
      description:
        type: 'String'
      owner:
        type: 'User!'
      boards:
        type: '[Board!]!'
