URI:
  type: custom-scalar
  config:
    description: 'An RFC 3986, RFC 3987, and RFC 6570 (level 4) compliant URI string.'
    serialize: ["App\\GraphQL\\Type\\URIType", 'serialize']
    parseValue: ["App\\GraphQL\\Type\\URIType", 'parseValue']
    parseLiteral: ["App\\GraphQL\\Type\\URIType", 'parseLiteral']
