User:
  type: object
  inherits: [Node]
  config:
    name: User
    interfaces: ['Node']
    fields:
      id:
        type: 'ID!'
      username:
        type: 'String!'
        resolve: '@=value.getRealUsername()'
      email:
        type: 'String!'
      tickets:
        type: '[Ticket!]!'
      teams:
        type: '[Team!]!'
      ownedTeams:
        type: '[Team!]!'
